let product_data = [{
    "id":0,
    "condtion":"Pre Owned",
    "image":"../images/view1.jpg",
    "category":"Building",
    "address":"Yale Street, Cubao , Kaunlaran, Quezon City",
    "floor":"250",
    "lot":"300",
    "bedroom":"7",
    "bathroom":"4",
    "garage":"1",
    "price":"₱26,500,000",
  },
  {
    "id":1,
    "condtion":"Pre Owned",
    "image":"../images/view1.jpg",
    "category":"Building",
    "address":"Filinvest 2, Batasan Hills, Quezon City",
    "floor":"302",
    "lot":"240",
    "bedroom":"4",
    "bathroom":"4",
    "garage":"1",
    "price":"₱6,500,000",
  },
  {
    "id":2,
    "condtion":"New",
    "image":"../images/view1.jpg",
    "category":"Building",
    "address":"Filinvest East Home, Cainta, Rizal",
    "floor":"190",
    "lot":"142",
    "bedroom":"4",
    "bathroom":"3",
    "garage":"1",
    "price":"₱14,500,000",
  },
  {
    "id":3,
    "condtion":"New",
    "image":"../images/view1.jpg",
    "category":"Building",
    "address":"Yale Street, Cubao , Kaunlaran, Quezon City",
    "floor":"250",
    "lot":"300",
    "bedroom":"4",
    "bathroom":"3",
    "garage":"1",
    "price":"₱2,500,000",
  },
  {
    "id":4,
    "condtion":"Pre Owned",
    "image":"../images/view1.jpg",
    "category":"Building",
    "address":"Quezon City, UP Village, Quezon City",
    "floor":"350",
    "lot":"170",
    "bedroom":"4",
    "bathroom":"4",
    "garage":"1",
    "price":"₱35,500,000",
  },
  {
    "id":5,
    "condtion":"Pre Owned",
    "image":"../images/view1.jpg",
    "category":"Building",
    "address":"SMDC Shell Residences, Bagong Silang, Mandaluyong City",
    "floor":"28",
    "lot":"-",
    "bedroom":"1",
    "bathroom":"1",
    "garage":"-",
    "price":"₱6,500,000",
  }
];